// Sample Work Order Data
const workOrdersData = [
    {
        id: 'WO-00149331',
        status: 'New',
        priority: 'Critical',
        trade: 'Plumbing',
        issue: 'Toilet Repair - Emergency',
        storeName: 'Warhammer - Rancho Vista #0407',
        city: 'Cerritos',
        state: 'CA',
        storeMall: 'Rancho Vista Shopping Center',
        storeEmail: 'store0407@warhammer.com',
        nteAmount: 550.00,
        contractorName: null,
        dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        isOverdue: true,
        daysOverdue: 3
    },
    {
        id: 'WO-00150116',
        status: 'Scheduled',
        priority: 'High',
        trade: 'Fire Services',
        issue: 'Fire Extinguisher Inspection',
        storeName: 'Purple Store #1432',
        city: 'Columbus',
        state: 'OH',
        storeMall: 'Easton Town Center',
        storeEmail: 'store1432@purple.com',
        nteAmount: 320.00,
        contractorName: 'FireSafe Systems',
        scheduledDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150125',
        status: 'On-site/In Progress',
        priority: 'Medium',
        trade: 'Janitorial/Cleaning Services',
        issue: 'Window Cleaning - Quarterly',
        storeName: 'Purple Store #0982',
        city: 'Irvine',
        state: 'CA',
        storeMall: 'Irvine Spectrum Center',
        storeEmail: 'store0982@purple.com',
        nteAmount: 450.00,
        contractorName: 'CleanPro Services',
        dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150113',
        status: 'Scheduled',
        priority: 'High',
        trade: 'HVAC-R',
        issue: 'HVAC Preventative Maintenance',
        storeName: 'Purple Store #2847',
        city: 'Austin',
        state: 'TX',
        storeMall: 'The Domain',
        storeEmail: 'store2847@purple.com',
        nteAmount: 650.00,
        contractorName: 'CoolTech HVAC',
        scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150146',
        status: 'Work Complete',
        priority: 'Low',
        trade: 'Locks/Safes/Security',
        issue: 'Door Lock Replacement',
        storeName: 'Purple Store #1209',
        city: 'Farmington',
        state: 'UT',
        storeMall: 'Station Park',
        storeEmail: 'store1209@purple.com',
        nteAmount: 420.00,
        invoiceAmount: 420.00,
        contractorName: 'SecureLock Pro',
        completedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150092',
        status: 'New',
        priority: 'Medium',
        trade: 'Pest Control',
        issue: 'Pest Control Prevention',
        storeName: 'Purple Store #3118',
        city: 'San Marcos',
        state: 'TX',
        storeMall: 'Tanger Outlets',
        storeEmail: 'store3118@purple.com',
        nteAmount: 275.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00149887',
        status: 'Proposal Submitted',
        priority: 'Medium',
        trade: 'Lighting',
        issue: 'Interior Lighting Upgrade',
        storeName: 'Purple Store #0484',
        city: 'Bakersfield',
        state: 'CA',
        nteAmount: 2450.00,
        contractorName: 'Bright Electric Co',
        dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150201',
        status: 'Assigned',
        priority: 'Critical',
        trade: 'Plumbing',
        issue: 'Water Leak - Urgent',
        storeName: 'Purple Store #1503',
        city: 'Las Vegas',
        state: 'NV',
        nteAmount: 800.00,
        contractorName: 'PlumbRight Services',
        dueDate: new Date(Date.now()),
        createdDate: new Date(Date.now() - 2 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150215',
        status: 'On-site/In Progress',
        priority: 'High',
        trade: 'Fire Services',
        issue: 'Fire Alarm System Repair',
        storeName: 'Purple Store #2001',
        city: 'Phoenix',
        state: 'AZ',
        nteAmount: 950.00,
        contractorName: 'FireSafe Systems',
        dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150228',
        status: 'New',
        priority: 'High',
        trade: 'Electrical',
        issue: 'Electrical Panel Inspection',
        storeName: 'Purple Store #1432',
        city: 'Columbus',
        state: 'OH',
        nteAmount: 850.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150242',
        status: 'Scheduled',
        priority: 'Medium',
        trade: 'HVAC-R',
        issue: 'AC Unit Replacement',
        storeName: 'Purple Store #3201',
        city: 'Miami',
        state: 'FL',
        nteAmount: 3500.00,
        contractorName: 'CoolTech HVAC',
        scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150256',
        status: 'Work Complete',
        priority: 'Medium',
        trade: 'Plumbing',
        issue: 'Sink Faucet Replacement',
        storeName: 'Purple Store #0521',
        city: 'Denver',
        state: 'CO',
        nteAmount: 380.00,
        invoiceAmount: 375.00,
        contractorName: 'PlumbRight Services',
        completedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150270',
        status: 'Assigned',
        priority: 'Medium',
        trade: 'Locks/Safes/Security',
        issue: 'Security System Update',
        storeName: 'Purple Store #2756',
        city: 'Atlanta',
        state: 'GA',
        nteAmount: 1100.00,
        contractorName: 'SecureLock Pro',
        dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150284',
        status: 'On-site/In Progress',
        priority: 'Low',
        trade: 'Janitorial/Cleaning Services',
        issue: 'Deep Cleaning Service',
        storeName: 'Purple Store #1892',
        city: 'Seattle',
        state: 'WA',
        nteAmount: 520.00,
        contractorName: 'CleanPro Services',
        dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150298',
        status: 'New',
        priority: 'Critical',
        trade: 'Electrical',
        issue: 'Power Outage Investigation',
        storeName: 'Purple Store #2105',
        city: 'Portland',
        state: 'OR',
        nteAmount: 1200.00,
        contractorName: null,
        dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 6 * 60 * 60 * 1000),
        isOverdue: true,
        daysOverdue: 1
    },
    {
        id: 'WO-00150312',
        status: 'Work Complete',
        priority: 'High',
        trade: 'Electrical',
        issue: 'Lighting Fixture Installation',
        storeName: 'Purple Store #1892',
        city: 'Seattle',
        state: 'WA',
        nteAmount: 1250.00,
        invoiceAmount: 1245.00,
        contractorName: 'Bright Electric Co',
        completedDate: new Date(Date.now()),
        dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150326',
        status: 'Scheduled',
        priority: 'High',
        trade: 'Pest Control',
        issue: 'Monthly Pest Control Service',
        storeName: 'Purple Store #3118',
        city: 'San Marcos',
        state: 'TX',
        nteAmount: 180.00,
        contractorName: 'PestFree Solutions',
        scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150340',
        status: 'Assigned',
        priority: 'Low',
        trade: 'General Maintenance',
        issue: 'Monthly Maintenance Check',
        storeName: 'Purple Store #2105',
        city: 'Portland',
        state: 'OR',
        nteAmount: 500.00,
        contractorName: 'MaintainPro Services',
        dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150354',
        status: 'New',
        priority: 'Medium',
        trade: null,
        issue: 'Heating System Repair',
        storeName: 'Purple Store #2847',
        city: 'Austin',
        state: 'TX',
        nteAmount: null,
        contractorName: null,
        dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 12 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150368',
        status: 'On-site/In Progress',
        priority: 'High',
        trade: 'Plumbing',
        issue: 'Pipe Leak Repair',
        storeName: 'Purple Store #1503',
        city: 'Las Vegas',
        state: 'NV',
        nteAmount: 680.00,
        contractorName: 'PlumbRight Services',
        dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150382',
        status: 'Bid Out',
        priority: 'Medium',
        trade: 'Electrical',
        issue: 'Panel Upgrade Project',
        storeName: 'Purple Store #2201',
        city: 'San Diego',
        state: 'CA',
        nteAmount: 3500.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150396',
        status: 'Awaiting Parts',
        priority: 'High',
        trade: 'HVAC-R',
        issue: 'Compressor Replacement',
        storeName: 'Purple Store #1892',
        city: 'Seattle',
        state: 'WA',
        nteAmount: 2800.00,
        contractorName: 'CoolTech HVAC',
        dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150410',
        status: 'On Hold',
        priority: 'Medium',
        trade: 'Plumbing',
        issue: 'Bathroom Renovation',
        storeName: 'Purple Store #2756',
        city: 'Atlanta',
        state: 'GA',
        nteAmount: 15000.00,
        contractorName: 'PlumbRight Services',
        dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150424',
        status: 'Follow-up Required',
        priority: 'High',
        trade: 'Electrical',
        issue: 'Outlet Installation',
        storeName: 'Purple Store #2105',
        city: 'Portland',
        state: 'OR',
        nteAmount: 450.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150438',
        status: 'Quote Requested',
        priority: 'Medium',
        trade: 'Fire Services',
        issue: 'Sprinkler System Installation',
        storeName: 'Purple Store #3201',
        city: 'Miami',
        state: 'FL',
        nteAmount: 5000.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150452',
        status: 'Dispatched',
        priority: 'Critical',
        trade: 'Plumbing',
        issue: 'Water Main Break',
        storeName: 'Purple Store #1503',
        city: 'Las Vegas',
        state: 'NV',
        nteAmount: 2500.00,
        contractorName: 'PlumbRight Services',
        dueDate: new Date(Date.now()),
        createdDate: new Date(Date.now() - 2 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150466',
        status: 'New',
        priority: 'High',
        trade: 'Fire Services',
        issue: 'Fire Alarm System Inspection',
        storeName: 'Purple Store #2201',
        city: 'San Diego',
        state: 'CA',
        nteAmount: 680.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 8 * 60 * 60 * 1000),
        isOverdue: false
    },
    {
        id: 'WO-00150480',
        status: 'New',
        priority: 'Medium',
        trade: 'General Maintenance',
        issue: 'Flooring Repair',
        storeName: 'Purple Store #2756',
        city: 'Atlanta',
        state: 'GA',
        nteAmount: 950.00,
        contractorName: null,
        dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        createdDate: new Date(Date.now() - 4 * 60 * 60 * 1000),
        isOverdue: false
    }
];

