// Sample Store Data - Multiple stores associated with the user's account
const storesData = [
    {
        id: 'store-0474',
        accountName: 'Warhammer - Silas Creek Crossing',
        storeNumber: '#0474',
        corpId: '0474',
        phone: '+1 743-643-4182',
        phoneExt: '',
        shippingStreet: '3246 Silas Creek Parkway',
        unit: 'Unit A',
        city: 'Winston-Salem',
        state: 'NC',
        zipCode: '27103-3011',
        region: 'Region 2',
        parentCompany: 'Warhammer Corporation',
        account: 'Warhammer - Silas Creek Crossing #0474',
        status: 'Active',
        storeManager: 'Sarah Johnson',
        managerPhone: '+1 336-555-1234',
        managerEmail: 'sarah.johnson@warhammer.com',
        mall: 'Silas Creek Crossing Mall',
        projectManager: 'Michael Chen',
        deactivationReason: ''
    },
    {
        id: 'store-0407',
        accountName: 'Warhammer - Rancho Vista',
        storeNumber: '#0407',
        corpId: '0407',
        phone: '+1 562-402-1893',
        phoneExt: '',
        shippingStreet: '12345 South Street',
        unit: 'Unit B',
        city: 'Cerritos',
        state: 'CA',
        zipCode: '90703',
        region: 'Region 1',
        parentCompany: 'Warhammer Corporation',
        account: 'Warhammer - Rancho Vista #0407',
        status: 'Active',
        storeManager: 'David Martinez',
        managerPhone: '+1 562-555-5678',
        managerEmail: 'david.martinez@warhammer.com',
        mall: 'Rancho Vista Shopping Center',
        projectManager: 'Jennifer Lee',
        deactivationReason: ''
    },
    {
        id: 'store-0982',
        accountName: 'Purple Store',
        storeNumber: '#0982',
        corpId: '0982',
        phone: '+1 949-555-1234',
        phoneExt: '123',
        shippingStreet: '670 Spectrum Center Drive',
        unit: 'Suite 200',
        city: 'Irvine',
        state: 'CA',
        zipCode: '92618',
        region: 'Region 1',
        parentCompany: 'Purple Corporation',
        account: 'Purple Store #0982',
        status: 'Active',
        storeManager: 'Emily Rodriguez',
        managerPhone: '+1 949-555-2345',
        managerEmail: 'emily.rodriguez@purple.com',
        mall: 'Irvine Spectrum Center',
        projectManager: 'Robert Kim',
        deactivationReason: ''
    },
    {
        id: 'store-2105',
        accountName: 'Purple Store',
        storeNumber: '#2105',
        corpId: '2105',
        phone: '+1 503-555-9876',
        phoneExt: '',
        shippingStreet: '1234 NW 23rd Avenue',
        unit: '',
        city: 'Portland',
        state: 'OR',
        zipCode: '97210',
        region: 'Region 3',
        parentCompany: 'Purple Corporation',
        account: 'Purple Store #2105',
        status: 'Active',
        storeManager: 'James Wilson',
        managerPhone: '+1 503-555-3456',
        managerEmail: 'james.wilson@purple.com',
        mall: 'NW 23rd Shopping District',
        projectManager: 'Lisa Anderson',
        deactivationReason: ''
    },
    {
        id: 'store-0521',
        accountName: 'Warhammer - Downtown Plaza',
        storeNumber: '#0521',
        corpId: '0521',
        phone: '+1 415-555-2468',
        phoneExt: '',
        shippingStreet: '789 Market Street',
        unit: 'Floor 2',
        city: 'San Francisco',
        state: 'CA',
        zipCode: '94102',
        region: 'Region 1',
        parentCompany: 'Warhammer Corporation',
        account: 'Warhammer - Downtown Plaza #0521',
        status: 'Active',
        storeManager: 'Patricia Brown',
        managerPhone: '+1 415-555-4567',
        managerEmail: 'patricia.brown@warhammer.com',
        mall: 'Downtown Plaza',
        projectManager: 'Thomas White',
        deactivationReason: ''
    },
    {
        id: 'store-1876',
        accountName: 'Purple Store',
        storeNumber: '#1876',
        corpId: '1876',
        phone: '+1 206-555-3691',
        phoneExt: '',
        shippingStreet: '456 Pike Street',
        unit: '',
        city: 'Seattle',
        state: 'WA',
        zipCode: '98101',
        region: 'Region 3',
        parentCompany: 'Purple Corporation',
        account: 'Purple Store #1876',
        status: 'Active',
        storeManager: 'Christopher Davis',
        managerPhone: '+1 206-555-5678',
        managerEmail: 'christopher.davis@purple.com',
        mall: 'Pike Street Market',
        projectManager: 'Amanda Taylor',
        deactivationReason: ''
    },
    {
        id: 'store-0633',
        accountName: 'Warhammer - Westfield Mall',
        storeNumber: '#0633',
        corpId: '0633',
        phone: '+1 310-555-7412',
        phoneExt: '',
        shippingStreet: '10250 Santa Monica Boulevard',
        unit: 'Unit 205',
        city: 'Los Angeles',
        state: 'CA',
        zipCode: '90067',
        region: 'Region 1',
        parentCompany: 'Warhammer Corporation',
        account: 'Warhammer - Westfield Mall #0633',
        status: 'Active',
        storeManager: 'Jessica Garcia',
        managerPhone: '+1 310-555-6789',
        managerEmail: 'jessica.garcia@warhammer.com',
        mall: 'Westfield Mall',
        projectManager: 'Daniel Moore',
        deactivationReason: ''
    },
    {
        id: 'store-2241',
        accountName: 'Purple Store',
        storeNumber: '#2241',
        corpId: '2241',
        phone: '+1 303-555-8520',
        phoneExt: '',
        shippingStreet: '1400 Larimer Street',
        unit: '',
        city: 'Denver',
        state: 'CO',
        zipCode: '80202',
        region: 'Region 2',
        parentCompany: 'Purple Corporation',
        account: 'Purple Store #2241',
        status: 'Active',
        storeManager: 'Kevin Jackson',
        managerPhone: '+1 303-555-7890',
        managerEmail: 'kevin.jackson@purple.com',
        mall: 'Larimer Square',
        projectManager: 'Nicole Harris',
        deactivationReason: ''
    },
    {
        id: 'store-0215',
        accountName: 'Warhammer - Central Avenue',
        storeNumber: '#0215',
        corpId: '0215',
        phone: '+1 818-241-0068',
        phoneExt: '',
        shippingStreet: '919 S Central Ave',
        unit: 'Unit A',
        city: 'Glendale',
        state: 'CA',
        zipCode: '91204-2095',
        region: 'Region 1',
        parentCompany: 'Warhammer Corporation',
        account: 'Warhammer - Central Avenue #0215',
        status: 'Active',
        storeManager: 'Kyle Holl',
        managerPhone: '+1 818-555-1234',
        managerEmail: 'kyle.holl@warhammer.com',
        mall: '',
        projectManager: '',
        deactivationReason: ''
    }
];
